---
title: "R Notebook"
output: 
  github_document:
    toc: true
    dev: png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
library(microbenchmark)
library(devtools)
```

# Load glmnetverissimo for tests

```{r}
devtools::load_all('.')
```

```{r}
data("CoxExample")
ntimes <- 3
```


```{r}
new.x <- matrix(rep(x, 1), nrow = 1000, ncol = 30)
microbenchmark::microbenchmark(
  glmnetverissimo::cv.glmnet(new.x, y, family = 'cox', mc.cores = 3)
  , times = 100)
```

## x10

```{r}
new.x <- matrix(rep(x, 10), nrow = 1000, ncol = 300)
new.x <- new.x + rnorm(length(new.x))
microbenchmark::microbenchmark(
  glmnetverissimo::cv.glmnet(new.x, y, family = 'cox', mc.cores = 3)
  , times = ntimes)
```

## x100

```{r}
new.x <- matrix(rep(x, 100), nrow = 1000, ncol = 3000)
new.x <- new.x + rnorm(length(new.x))
microbenchmark::microbenchmark(
  glmnetverissimo::cv.glmnet(new.x, y, family = 'cox', mc.cores = 3)
  , times = ntimes)
```

## Unload libraries

```{r}
devtools::unload('.')
```

## Load glmnet and doMC library


```{r}
library(doMC)
registerDoMC(cores=3)
library(glmnet)
```

## x1

```{r}
new.x <- matrix(rep(x, 1), nrow = 1000, ncol = 30)
microbenchmark::microbenchmark(
  glmnet::cv.glmnet(new.x, y, family = 'cox', parallel = T)
  , times = 100)
```

## x10

```{r}
new.x <- matrix(rep(x, 10), nrow = 1000, ncol = 300)
new.x <- new.x + rnorm(length(new.x))
microbenchmark::microbenchmark(
  glmnet::cv.glmnet(new.x, y, family = 'cox', parallel = T)
  , times = ntimes)
```

## x100

```{r}
new.x <- matrix(rep(x, 100), nrow = 1000, ncol = 3000)
new.x <- new.x + rnorm(length(new.x))
microbenchmark::microbenchmark(
  glmnet::cv.glmnet(new.x, y, family = 'cox', parallel = T)
  , times = ntimes)
```

## Unload glmnet

```{r}
unload(inst('glmnet'))
```

# Session Information

```{r}
sessionInfo()
```

